cloudsec/cloudsec/urls.py
from django.urls import path
from cloudsec import views
app_name = 'cloudsec'
urlpatterns = [ 
    path('create', views.cloudsec_index ,name="index"),
    path('files', views.cloudsec_libraries ,name="libraries"),
    path('scan/<int:lib_id>', views.library_scan , name="lib_scan"),
    path('check/<int:lib_id>', views.query_db , name="vuln_check"),
    path('delete_librabry/<int:librabry_id>', views.delete_librabry , name="delete_librabry"),
    path('cve_scan', views.cve_scan , name="cve_scan"),
    # path('scan_all', views.scan_all , name="scan_all"),


    
 
]

cloudsec/home/urls.py
from django.urls import path
from home import views
app_name = 'home'
urlpatterns = [ 
    
    path('', views.home_login , name="login"),
    path('logout', views.home_logout ,name="logout"),
    path('profile', views.home_profile ,name="profile"),


]

cloudsec/security/urls.py
from django.contrib import admin
from django.urls import path
from home import urls as home_urls
from mainmenu import urls as mainmenu_urls
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from cloudsec import urls as dashboard_urls

urlpatterns = [
    path('home/', include(home_urls, namespace="home")),
    path('mainmenu/', include(mainmenu_urls, namespace="mainmenu")),
    path('cloudsec/', include(dashboard_urls, namespace="dashboard")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'VULNCHECK'
admin.site.site_title = 'VULNCHECK'

cloudsec/cloudsec/models.py
from django.db import models


class Library(models.Model):
    STATUS = (
        ('', '------------'),
        ('application', 'Deployment File'),
        # ('services', 'KB LIST File'),
 
        
    )
    organization = models.CharField(default=None ,max_length=100)
    application_name = models.CharField(default=None ,max_length=100)
    library_list = models.FileField(upload_to='uploads/')
    data_mode = models.CharField(blank=True , default='no' ,max_length=100 , choices = STATUS)
    created_at = models.DateField(default=None)
    updated_at = models.DateField(default=None)
    created_by = models.IntegerField(default=None)

    def __str__(self):
        return '%s' % self.application_name

class CVE_Scan(models.Model):
    

    cve_name = models.CharField(default=None ,max_length=100)


    def __str__(self):
        return '%s' % self.cve_name

cloudsec/cloudsec/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator
from cloudsec.models import Library ,CVE_Scan 

# model form 
from django.db import models
# from django.forms import ModelForm , Textarea , ModelChoiceField , Select  


class Library_Form(forms.ModelForm):

    class Meta:
        model = Library
        
        
        fields = ['organization','application_name','library_list' ,'data_mode']

             
        widgets = {
            'organization': forms.TextInput(attrs={
                "type" : "text",
                "class":"form-control"
            }),
            'application_name': forms.TextInput(attrs={
                "type" : "text",
                "class":"form-control"
            }),
            'library_list': forms.ClearableFileInput(attrs={
                "class":"form-control",
                "id":"picture",
                "type" : "file",
            }),
            'data_mode': forms.Select(attrs={
                "type" : "text",
                "class":"form-control custom-select",
                "id":"data_mode"
            }),
           
        }


class  CVE_Scan_Form(forms.ModelForm):
    class Meta:
        model = CVE_Scan
        
        
        fields = ['cve_name']

             
        widgets = {
            
            'cve_name': forms.TextInput(attrs={
                "type" : "text",
                "class":"form-control"
            }),
         
           
        }

cloudsec/cloudsec/views.py
from django.shortcuts import render
import calendar
from datetime import datetime
from django.contrib.auth.decorators import login_required , permission_required
from pypi_simple import PyPISimple 
from cloudsec.forms import Library_Form , CVE_Scan_Form
from cloudsec.models import  Library
from django.contrib import messages
from django.utils import timezone
from django.urls import reverse
from django.http import HttpResponseRedirect
import vulners  
from django.core.mail import send_mail


@login_required
def cloudsec_index(request):
    form = None
    url = "cloudsec/index.html" 
    if request.method == 'POST':
        form = Library_Form(request.POST, request.FILES)
        if(form.is_valid()):
            data = form.save(commit=False)
            data.created_at = timezone.now()
            data.updated_at = timezone.now()
            data.created_by = request.user.id
            data.save()
            messages.add_message(request, messages.INFO, 'Application Libraries stored successful')
            return HttpResponseRedirect(reverse('cloudsec:libraries'))
     
    else:
        form = Library_Form()
    
    context = {
        
        'title': "Add Requirement File",
        'form':form
        
    } 
     
    return render(request , url , context)

@login_required
def cloudsec_libraries(request):
    libraries = Library.objects.all().order_by('-id')
    url = "cloudsec/list_librabries.html" 
    # send_mail(
    #     'Payment',
    #     'find payment.',
    #     'kidkudzy@gmail.com',
    #     ['kmakufa@outlook.com', 'promiseksystems@gmail.com'],
    #     fail_silently=False,
    # )
    context = {
        
        'title': "Add Libraries",
        'libraries':libraries
        
    } 


    return render(request , url , context)



# @login_required
# def library_scan(request ,lib_id=None):
#     library = Library.objects.filter(id=lib_id).order_by('-id')
#     f = open(library[0].library_list.path, "r")
#     print("------------------")

#     lines = f.readlines()
#     for line in lines:
#         print(line)
#     print("------------------")
#     f.close()
#     context = {
#         "item":library[0], 
#         "lines":lines
#     }
#     return render(request, 'cloudsec/library_view.html', context)
    


@login_required
def library_scan(request ,lib_id=None):
    library = Library.objects.filter(id=lib_id).order_by('-id')
    f = open(library[0].library_list.path, "r")
    print("------------------")

    lines = f.readlines()
    for line in lines:
        print(line)
    print("------------------")
    f.close()
    context = {
        "item":library[0], 
        "lines":lines
    }

    
    return render(request, 'cloudsec/library_view.html', context)
    
@login_required
def query_db(request ,lib_id=None):
    library = Library.objects.filter(id=lib_id).order_by('-id')
    f = open(library[0].library_list.path, "r")
    print("------------------")

    lines = f.readlines()

    data = []
    count =0
    org_score = 0
    Issues = []
    Affected_Cve = []
    url_path = ""
   
    for line in lines:
        # here comes the vuln scanner logic
        sep = '=='
        stripped = line.split(sep, 1)[0]
        lib_version = line.split(sep, 1)[1]
        is_safe = False
        
        # print(line.strip())
        # print("-------without end-------")
        # print(line.split(sep, 1)[0])
        # print("------with end-----")
      
        # check updates and security
        with PyPISimple() as client:
            requests_page = client.get_project_page(stripped.strip())
        
        requests_page = client.get_project_page(stripped.strip())
        pkg_params = {}

        if(library[0].data_mode == 'application'):
            url_path = "cloudsec/app_cloudsec.html"
            
            try:
                try:
                    vulners_api = vulners.Vulners(api_key="4QIYDKA0NXPHUWXJNQYLISIZEZZH8FM25YNK0L518VOWJJEOWO81XGMH2KSL81KJ")
                    results = vulners_api.softwareVulnerabilities(stripped.strip(), lib_version.strip())
                    # print(len(stripped.strip()))
                    # print(len(lib_version.strip()))
                    # results = vulners_api.softwareVulnerabilities("httpd", "1.3")
                    exploit_list = results.get('exploit')
                    vulnerabilities_list = [results.get(key) for key in results if key not in ['info', 'blog', 'bugbounty']]
                    print("vulneralibity type_____"+vulnerabilities_list[0][0]['type'])
                    print(vulnerabilities_list[0][0]['title'])
                    Issues = vulnerabilities_list[0][0]
                    

                except:
                    is_safe = True
                    print("safe")
                pkg = requests_page.packages[0]
                pkg_params = {"name":pkg.project , "current_version":lib_version.strip() , "latest_version":pkg.version ,"digest":pkg.get_digests()['sha256'] , 'url':pkg.url ,'is_signed':pkg.has_sig ,'is_safe':is_safe ,'issue_title':Issues}
            except:
                pkg_params = {"name":stripped.strip() , "current_version":lib_version.strip() , "latest_version":"n/a" ,"digest":"n/a",'is_safe':is_safe ,'issue_title':Issues}

             # scan safety-db
            
            print("------check below-1-----------")
            # append scores and count 
            print()
            try:
                if isinstance(Issues['cvss']['score'], float):
                    org_score = org_score + Issues['cvss']['score']
                else:
                    print("not numeric")
            except:
                print("no score")
            count = count + 1


            print("------check below-2-----------")
            # print(pkg_params['issue_title']['cvss']['score'])

        
       

        data.append(pkg_params.copy())
    
        
           
    print(str(org_score)+"  "+str(count))
    print("------------------")
    f.close()
    context = {
        "item":library[0],
        "data":data ,
        'score':org_score / count , 
        'count':count ,
        'org_score':org_score ,
       
    }
    return render(request, url_path, context)
@login_required
def delete_librabry(request ,librabry_id=None):
    library = Library.objects.get(pk=librabry_id)
    library.delete()
    messages.add_message(request, messages.INFO, 'Library deleted')
    return HttpResponseRedirect('/cloudsec/files')


@login_required
def cve_scan(request):
    form = None
    url = "cloudsec/view_by_cve.html" 
    cve_data = []
    if request.method == 'POST':
        url = "cloudsec/cve_results.html"
        form = CVE_Scan_Form(request.POST)
        if(form.is_valid()):
           
            data = form.cleaned_data['cve_name']
            print("^^^^^^^^^^^")

            vulners_api = vulners.Vulners(api_key="4QIYDKA0NXPHUWXJNQYLISIZEZZH8FM25YNK0L518VOWJJEOWO81XGMH2KSL81KJ")
            cve_data = vulners_api.document(data)
            print(cve_data)
        
     
    else:
        form = CVE_Scan_Form()
    
    context = {
        
        'title': "Scan by Cve",
        'form':form,
        'cve_data':cve_data
        
    } 
     
    return render(request , url , context)

cloudsec/cloudsec/templates/cloudsec/app_cloudsec.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="row">
  <div class="col-12 m-auto">
  <h4>Organization Score : {{score|floatformat:2}} / 10 </h4>
  <hr>
  <h5>Scanned packages : {{count}}</h5>
  <hr>
 


    
   
  </div>
</div>
    <div class="row">
        <div class="col-md-6">
            <table id="datatable" class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                <thead>
                <tr>
                    
                    <th>Library Name </th>
                    
                    <th>Installed Version</th>
                    {% comment %} <th>Latest Version</th> {% endcomment %}
                    <th>Digest </th>
                    <th>Url </th>
                    <th>Is Signed </th>
                    <th>Is Safe </th>
                    <th>Actions  </th>
                    
                
                </tr>
                </thead>


                <tbody>
             
                {% for item in data %}
                
                    <tr>
                        <td>{{item.name}}</td>
                    
                        
                        <td>{{item.current_version}}</td>
                        {% comment %} <td>{{item.latest_version}}</td> {% endcomment %}
                        <td>{{item.digest}}</td>
                        <td>
                           <a href="{{item.url}}">{{item.name}}</a> 
                        </td>
                        <td> 
                            {% if item.is_signed == None %}
                            <p class="text-warning">Unspecified</p>
                            {% else %}
                            <p class="text-success">Signed</p>
                            {% endif %}
                        </td>

                       
                            {% if item.is_safe %}
                             <td> <p class="text-success">Safe</p></td>
                             
                            {% else %}
                            
                            <td><p class="text-danger">Vulnerable</p></td>
                            
                            <td>
                              <a data-toggle="modal" data-target="#modal_{{item.name}}" class="btn btn-sm btn-outline-success waves-effect waves-light"><i class="fas fa-eye"></i></a>|
                            {% comment %} <button class="btn btn-sm btn-primary"> Issues</button> {% endcomment %}
                            </td>
                            {% include './issues.html' %}
                            {% endif %}
                        

                    
                       
                    
                    
                      
                    
                    </tr>
                {% endfor %}
           
          
                </tbody>
            </table>

        </div>
       
      </div>



  {% endblock %}

cloudsec/cloudsec/templates/cloudsec/cve_results.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

    <div class="row">
        <div class="col-md-12">
                <div class="row">
                    <div class="col-sm-4">
                       ID
                    </div>
                    <div class="col-sm-8">
                        {{cve_data.id}}
                    </div>
                </div>

        </div>
    </div>


    <div class="row">
        <div class="col-md-12">
                <div class="row">
                    <div class="col-sm-4">
                       Score
                    </div>
                    <div class="col-sm-8">
                        {{cve_data.cvss.score}}
                    </div>
                </div>

        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
                <div class="row">
                    <div class="col-sm-4">
                       Description
                    </div>
                    <div class="col-sm-8">
                        {{cve_data.description}}
                    </div>
                </div>

        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
                <div class="row">
                    <div class="col-sm-4">
                       Affected Software
                    </div>
                    <div class="col-sm-8">
                        {% for afsoft in cve_data.affectedSoftware %}
                        <div class="row">
                            <div class="col-4">
                            CPN NAME
                            </div>
                            <div class="col-8">
                            {{afsoft.cpeName}}
                            </div>
                        </div>
                         <div class="row">
                            <div class="col-4">
                            NAME
                            </div>
                            <div class="col-8">
                            {{afsoft.name}}
                            </div>
                        </div>
                         <div class="row">
                            <div class="col-4">
                            Version
                            </div>
                            <div class="col-8">
                            {{afsoft.version}}
                            </div>
                        </div>
                        <hr>
                        {% endfor %}
                    </div>
                </div>

        </div>
    </div>



    

    



  {% endblock %}

cloudsec/cloudsec/templates/cloudsec/index.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<div class="container" id="container-wrapper">
    <div class="d-sm-flex align-items-center justify-content-between mb-4 ml-3">
    <h1 class="h3 mb-0 text-gray-800">{{title}}</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="./">Home</a></li>
        <li class="breadcrumb-item">Forms</li>
        <li class="breadcrumb-item active" aria-current="page">{{title}}</li>
    </ol>
    </div>

    {% comment %} <div class="container"> {% endcomment %}
        <div class="col-lg-12">
            <!-- Form Basic -->
            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">{{title}}</h6>
                </div>
                <div class="card-body">
                    <form action="" method="post" enctype="multipart/form-data" autocomplete="off">{% csrf_token %}
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                <div class="form-group mr-4 ml-4">
                                    <label> File Description<span class="text-danger"> * {{form.application_name.errors}}</span></label>
                                    {{form.application_name}}
                                    {% comment %} <small id="emailHelp" class="form-text text-muted">We'll never share your
                                    email with anyone else.</small> {% endcomment %}
                                </div>
                            </div>
                            
                            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                <div class="form-group mr-4 ml-4">
                                    <label> Input type<span class="text-danger"> * {{form.data_mode.errors}}</span></label>
                                    {{form.data_mode}}
                                </div>
                            </div>                            
                        </div>
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                <div class="form-group mr-4 ml-4">
                                    <label> Organization<span class="text-danger"> * {{form.organization.errors}}</span></label>
                                    {{form.organization}}
                                </div>
                            </div>  
                            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                <div class="form-group mr-4 ml-4">
                                    <label> Select File<span class="text-danger"> * {{form.library_list.errors}}</span></label>
                                    {{form.library_list}}
                                </div> 
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                <div class="form-group mr-4 ml-4">
                                    <label> {{form.phone_number.label_tag}}<span class="text-danger"> * {{form.phone_number.errors}}</span></label>
                                    {{form.phone_number}}
                                </div> 
                            </div>
                        </div>
                                     
                        <button type="submit" class="btn btn-primary mr-4 ml-4">Submit</button>
                    </form>
                </div>
            </div>
        </div>  

    <!-- Modal Logout -->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabelLogout"
    aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabelLogout">Ohh No!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to logout?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Cancel</button>
                <a href="login.html" class="btn btn-primary">Logout</a>
            </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block footer %}
 
  
{% endblock %}







cloudsec/cloudsec/templates/cloudsec/issues.html
                                   
                                                        
<!--  Modal content for the above example -->
<div class="modal fade bs-example-modal-lg" id="modal_{{item.name}}" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title mt-0" id="myLargeModalLabel">{{item.issue_title.title}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h4>Description </h4>
                <p>{{item.issue_title.description}}</p>
                    <hr>
                
                <div class="row">
                    <div class="col-sm-3">
                       Date Published
                    </div>
                    <div class="col-sm-4">
                        {{item.issue_title.published}}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        Vulnerability ID
                    </div>
                    <div class="col-sm-4">
                        {{item.issue_title.id}}
                    </div>
                </div>
                

                <div class="row">
                    <div class="col-sm-3">
                        CVE LIST
                    </div>
                    <div class="col-sm-4">
                        {{item.issue_title.cvelist}}
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-3">
                        CVS SCORE
                    </div>
                    <div class="col-sm-4">
                        {{item.issue_title.cvss.score}}
                    </div>
                </div>

               
                <hr>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal --> 

cloudsec/cloudsec/templates/cloudsec/library_view.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="row">
  <div class="col-12">
      
      <!-- <a href="#" class="btn btn-success float-right"></a> -->
   
  </div>
</div>
    <div class="row">
        <div class="col-md-6">
          <table id="datatable" class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                
            <tbody>
             
              <tr>
                <td><b>Application Name  </b> </td>
                <td>
                    <a href="{{item.library_list.path}}">{{item.application_name}}</a>
                    </td>
              </tr>

              {% for item in lines %}
                        <tr>
                            <td>{{item}}</td>
         
                        </tr>
                    {% endfor %}
    

            </tbody>
          </table>
        </div>
       
      </div>



  {% endblock %}

cloudsec/cloudsec/templates/cloudsec/list_librabries.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<div class="container-fluid" id="container-wrapper">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{title}}</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="./">Home</a></li>
        <li class="breadcrumb-item">Tables</li>
        <li class="breadcrumb-item active" aria-current="page">{{title}}</li>
    </ol>
    </div>

    <!-- Row -->
    <div class="row">
        <!-- DataTable with Hover -->
        <div class="col-lg-12">
            <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">{{title}}</h6>
                    <a href="{% url 'cloudsec:index' %}" class="btn btn-outline-primary mb-1">Add A File</a>
                </div>
                <div class="table-responsive p-3">
                    <table class="table align-items-center table-flush table-hover" id="dataTableHover">
                        <thead class="thead-light">
                            <tr>
                                <th>File No  </th>
                                <th>File Description  </th>
                                <th>File Type </th>
                                <th>Library list</th>
                                <th>Type</th>
                                <th>Operations  </th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>File Description  </th>
                                <th>File Type </th>
                                <th>Library list</th>
                                <th>Type</th>
                                <th>Operations  </th>
                            </tr>
                        </tfoot>
                        <tbody>
                           
                            {% for item in libraries %}
                            <tr>
                                <td>{{item.id}}</td>
                            <td>{{item.application_name}}</td>
                            <td>{{item.data_mode}}</td>
                            <td>{{item.library_list}}</td>
                            <td>{{item.data_mode}}</td>
                        
                           
                        
                        
                            <td>
                                <a href="{% url  'cloudsec:lib_scan' item.id  %}" class="btn btn-outline-primary waves-effect waves-light" >View Contents</a>
                                <a href="{% url  'cloudsec:vuln_check' item.id  %}" class="btn btn-outline-primary waves-effect waves-light" >Scan </a>
                                {% comment %} <a href="#" class="btn btn-outline-success waves-effect waves-light" >Edit</a>{% endcomment %}
                                <a href="{% url  'cloudsec:delete_librabry' item.id %}" class="btn btn-outline-danger waves-effect waves-light" onclick="alert('Are you sure you want to delete')" >Delete</a>
                                
                            </td>       
                        </tr>        
                            {% endfor %}
                       
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!--Row-->

    <!-- Modal Logout -->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabelLogout"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabelLogout">Ohh No!</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <p>Are you sure you want to logout?</p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Cancel</button>
            <a href="login.html" class="btn btn-primary">Logout</a>
        </div>
        </div>
    </div>
    </div>

</div>
{% endblock %}


{% block footer %}
  <!-- Page level plugins -->
  <script src="{% static "vendor/datatables/jquery.dataTables.min.js" %}"></script>
  <script src="{% static "vendor/datatables/dataTables.bootstrap4.min.js" %}"></script>

  <!-- Page level custom scripts -->
  <script>
    $(document).ready(function () {
      $('#dataTable').DataTable(); // ID From dataTable 
      $('#dataTableHover').DataTable(); // ID From dataTable with Hover
    });
  </script>  
{% endblock %}





